.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/release_issue.md, README.md
This still needs the correct video thumbnail image.
=> Fix readme logo and update link to demo video

cmd/collect.go, go.mod, go.sum, internal/collector/collector.go, internal/collector/tui.go, internal/metaquery/handlers.go
=> Quiet flag

internal/display/table.go
=> fix: table show command now correctly shows table description

internal/database/tables.go
=> refactor: sort columns before creating view to ensure they're correctly ordered

internal/metaquery/handler_inspect.go
=> fix: .inspect meta command no longer merges cells with same values. Closes #207

cmd/collect.go, internal/collector/collector.go
=> Added --progress flag to allow for toggling of active progres of collections, removed --timing flag as obsolete. Closes #191

internal/collector/status.go
=> refactor: updated status text for a collection with no active progress. Closes #210

cmd/collect.go, internal/collector/collector.go, internal/collector/tui.go
=> refactor: collection ui now displays 3 errors (count of additional) and link to file path containing the full error list

cmd/plugin.go, internal/plugin/installation_actions.go, internal/plugin/plugin_manager.go
=> refactor: update plugin install to pass WithGetMetadataFunc. Closes #229

CHANGELOG.md, cmd/collect.go, cmd/plugin.go, go.sum, internal/collector/collector.go, internal/collector/status.go, internal/database/tables.go, internal/display/partition.go, internal/filepaths/parquet.go, internal/filepaths/prune.go, internal/parquet/delete.go, internal/parquet/parquet_worker.go, internal/plugin_manager/plugin_manager.go
[Tailpipe v0.1.3](https://github.com/turbot/tailpipe/issues/250)
=> Release Tailpipe v0.1.3

cmd/plugin.go
=> refactor: plugin list returns help message when no plugins installed. Closes #240

internal/config/tailpipe_config.go, internal/display/table.go
=> refactor: updated table list/show cmds to include custom tables. Closes #252

internal/display/table.go
=> fix: table list correctly shows plugin for custom tables. Closes #277

internal/display/partition.go, internal/display/shared.go, internal/display/table.go
=> refactor: table and partition list/show commands use - for zero values. Closes #285

internal/display/format.go
=> refactor: format list and show now support type as well as instance. Closes #284

internal/database/tables.go, internal/display/table.go, internal/parquet/conversion_helpers.go, internal/parquet/conversion_helpers_test.go, internal/parquet/conversion_worker_test.go
=> refactor: table show not shows column types in lowercase. Closes #289

internal/collector/tui.go
=> refactor: updated tui to trigger updates each second. Closes #307

internal/parquet/conversion_helpers.go, internal/parquet/conversion_helpers_test.go, internal/parquet/conversion_worker_test.go, internal/plugin/plugin_manager.go
fix PluginManager.formatToProto to retrieve describe response using UnqualifiedName
=> fix: When the format plugin is different from the table plugin, resolution of the format before calling Collect fails. Closes #319

internal/display/table.go
=> fix: table introspection in json now displays descriptions correctly. Closes #323

internal/config/connection.go, internal/config/filter.go, internal/config/format.go, internal/config/partition.go, internal/config/table.go, internal/parse/decode.go
=> Ensure all resources which embed HclResourceImpl have a remain block to enable partial decoding

internal/cmdconfig/cmd_hooks.go, internal/logger/logger.go, internal/parse/load_config.go, internal/plugin/plugin_manager.go
=> EnsureCorePlugin is now called before loading TailpipeConfig to ensure we have all format presets registered

internal/display/format.go
=> refactor: added location to format list/show. Closes #283 

internal/display/source.go
=> refactor: added plugin to source list/show. Closes #337

CHANGELOG.md, go.mod, go.sum, internal/constants/plugin.go
=> Update Core to v0.2.5

.acceptance.goreleaser.yml, .github/workflows/01-tailpipe-release.yaml, .github/workflows/11-test-acceptance.yaml, .goreleaser.yml, CHANGELOG.md, Makefile, scripts/smoke_test.sh
[tailpipe v0.7.1](https://github.com/turbot/tailpipe/issues/581)
=> Release Tailpipe v0.7.1
